spring:
  application:
    name: techefx-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jpssasadara/environment-variable-repo.git


server:
  port: ${port:8888}

